//
// BadRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BadRequest: Codable, Hashable {

    public var type: String?
    public var title: String?
    public var name: String?
    public var status: Int?
    public var problems: Set<BadRequest>?

    public init(type: String? = nil, title: String? = nil, name: String? = nil, status: Int? = nil, problems: Set<BadRequest>? = nil) {
        self.type = type
        self.title = title
        self.name = name
        self.status = status
        self.problems = problems
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case title
        case name
        case status
        case problems
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(problems, forKey: .problems)
    }
}

