//
// TooManyRequests.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TooManyRequests: Codable, Hashable {

    /** A link to the error documentation. */
    public var type: String?
    /** A description of the error that occurred. */
    public var title: String?
    /** The HTTP status code. */
    public var status: Int?

    public init(type: String? = nil, title: String? = nil, status: Int? = nil) {
        self.type = type
        self.title = title
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case title
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

