//
// VideoSourceLiveStream.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This appears if the video is from a Live Record. */
public struct VideoSourceLiveStream: Codable, Hashable {

    /** The unique identifier for the live stream. */
    public var liveStreamId: String?
    public var links: [VideoSourceLiveStreamLink]?

    public init(liveStreamId: String? = nil, links: [VideoSourceLiveStreamLink]? = nil) {
        self.liveStreamId = liveStreamId
        self.links = links
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case liveStreamId
        case links
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(liveStreamId, forKey: .liveStreamId)
        try container.encodeIfPresent(links, forKey: .links)
    }
}

